#! /bin/bash

sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
mkdir -p ~/.config && cp -r dotfiles/* ~/.config/
mkdir -p ~/bin && cp bin/* ~/bin/
echo "export PATH=$PATH:$HOME/bin" >> ~/.bashrc

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

dnf install cargo git zsh neovim polybar gnome-session-xsession i3 rofi polybar arandr network-manager-applet blueman rofi-devel qalculate feh xdotool tmux fzf alacritty flatpak ripgrep
echo "export EDITOR=/usr/bin/nvim" >> ~/.bashrc
echo "export EDITOR=/usr/bin/nvim" >> ~/.zshrc

git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

dnf install octave octave-signal octave-statistics octave-symbolic ktechlab
dnf install xset bdftopcf texlive-scheme-full gimp inkscape ImageMagick zathura zathura-pdf-poppler 

dnf install vlc transmission steam mpd ncmpcpp pavucontrol

cp ~/.config/monitors.xml ~gdm/.config

hostnamectl set-hostname "Desktop"
git clone https://github.com/stark/siji && cd siji && ./install.sh -d ~/.fonts

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.zotero.Zotero
